import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import AuthSessionProvider from "@/components/providers/session-provider";

import ToastProvider from "@/components/providers/toast-provider";
import StoreProvider from "@/components/providers/redux-provider";
import { revalidatePath } from "next/cache";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // revalidatePath('/','layout')
  return (
    <AuthSessionProvider>
      <StoreProvider>
        <html lang="en">
          <body
            className={cn(
              inter.className,
              "min-h-screen bg-background font-sans antialiased"
            )}
          >
            <ToastProvider />
            {children}
          </body>
        </html>
      </StoreProvider>
    </AuthSessionProvider>
  );
}
